### ISSUE TITLE
Weblate: Complete Community localization checklist

### ISSUE THREAD

**Issue by silopolis** [silopolis/linuxcnc#19]
https://hosted.weblate.org/guide/linuxcnc/linuxcnc-docs/

 * [ ] Define translation instructions to give translators a guideline. 
 * [ ] Add screenshots to show where strings are being used ?
 * [ ] Add safe-html flag to avoid dangerous HTML from translators.
 * [ ] Enable add-on: Add missing languages
       Ensures a consistent set of languages is used for all components within a project.
